---
title: "Climbing Map"
author: "Federico Ferrari"
output: html_document

---

```{r setup, include=FALSE}
# leaflet map
# https://rstudio.github.io/leaflet/

library(tidyverse)
require(leaflet)
library(magrittr)
library(htmlwidgets)
require(shiny)

#### DATA FRAME CLIMBING PLACES
df = data.frame(matrix(ncol = 5, nrow = 0))
colnames(df) = c("place","lat","lng","type","year")
df[1,] = c("Pilot Mountain",36.342716,-80.474407,"Lead Climbing",2019)
df[2,] = c("Arco",45.929563, 10.889770,"Multi-pitch",2019)
df[3,] = c("Pietra di Bismantova",44.422374, 10.413951,"Multi-pitch",2019)
df[4,] = c("Passo Fedaia",46.456491, 11.860149,"Lead Climbing",2019)
df[5,] = c("Sasso Bruno - Passo Pordoi",46.489010, 11.796582,"Lead Climbing",2019)
df[6,] = c("Sasso Malga - Passo Sella",46.512370, 11.758457,"Lead Climbing",2019)
df[7,] = c("Torri del Sella",46.511015, 11.779914,"Multi-pitch",2019)
df[8,] = c("Lagoni",44.402991, 10.007326,"Lead Climbing",2019)


#### DATA FRAME CLIMBING ROUTES
df_routes = data.frame(matrix(ncol = 9, nrow = 0))
colnames(df_routes) = c("place","name","type","year","month","grade",
                        "vertical_meters","vertical_feet","pitches")
df_routes[1,] = c("Arco","La Bellezza della Venere","Multi-pitch",2019,"May","IV+",320,1050,9)
df_routes[2,] = c("Arco","Due Piccoli Pilastri","Multi-pitch",2019,"May","V+",150,500,4)
df_routes[3,] = c("Pietra di Bismantova","Zuffa/Ruggiero","Multi-pitch",2019,"July","V",105,350,5)
df_routes[4,] = c("Pietra di Bismantova","Italia 90 - variante Penna","Multi-pitch",2019,"July","6a",125,410,4)
df_routes[5,] = c("Torri del Sella","Spigolo Steger","Multi-pitch",2019,"July","IV+",140,460,5)
df_routes[6,] = c("Lagoni","Tettino","Lead Climbing",2019,"August","6a+",20,65,1)
df_routes[7,] = c("Lagoni","Cresta dello Sterpara","Multi-pitch",2019,"August","IV+",100,330,5)
df_routes[8,] = c("Pilot Mountain","Devil in the White House","Lead Climbing",2019,"September","10d",18,60,1)
df_routes[9,] = c("Pilot Mountain","Smooth Sailing","Lead Climbing",2019,"September","10a",25,80,1)
df_routes[10,] = c("Pilot Mountain","Pump Street","Lead Climbing",2019,"September","10a",20,65,1)




df$lat = as.numeric(df$lat) ; df$lng = as.numeric(df$lng)
m = leaflet(df) %>% addTiles()
m %>% addCircleMarkers(fill = FALSE)


getColor <- function(data) {
  sapply(data$type, function(type) {
    if(type == "Lead Climbing") {
      "red"
    } else if(type == "Multi-pitch") {
      "green"
    } else {
      "orange"
    } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = unname(getColor(df)),
  library = 'ion',
  markerColor = unname(getColor(df))
)

leaflet(df) %>% addTiles() %>%
  addAwesomeMarkers(~lng, ~lat, icon=icons, label=~as.character(type))


### EXAMPLE WITH POPUP
df_pietra = df_routes %>% 
  filter(place == "Pietra di Bismantova")

content <- paste(sep = "<br/>",
                 "<b><a href='http://www.samurainoodle.com'>Samurai Noodle</a></b>",
                 "606 5th Ave. S",
                 "Seattle, WA 98138"
)


create_popup = function(df_routes, name_place){
  
  df_int =filter(df_routes,place == name_place)
  n = nrow(df_int)
  
  html_title = paste("<head>
                     <style>
                     table, th, td {
                     border: 1px solid black;
                     border-collapse: collapse;
                     }
                     th, td {
                     padding: 5px;
                     }
                     th {
                     text-align: left;
                     }
                     </style>
                     </head>
                     <body>
                     
                     <h2>", 
                     name_place, 
                     #"</h2>
                     #<p>Write here something</p>",
                     "</h2>
                     <p></p>",
                     sep = "")
  
  
  
  
  if (n > 0){
    table_colnames = "<table style='width:100%'>
    <tr>
    <th>Name route</th>
    <th>year</th> 
    <th>grade</th> 
    <th>vertical meters</th>
    <th>pitches</th>
    </tr>"
    
    table_curr = paste(html_title,table_colnames,sep = "")
    
    for(j in 1:n){
      curr_row = paste("<tr>
                       <td>",df_int[j,2], "</td>
                       <td>",df_int[j,4] ,"</td>
                       <td>",df_int[j,6] ,"</td>
                       <td>",df_int[j,7] ,"</td>
                       <td>",df_int[j,9] ,"</td>
                       </tr>")
      
      table_curr = paste(table_curr,curr_row,sep = "")
      
    }
    html_fin = paste(table_curr,"</table>
                     
                     </body>",sep = "")
  }else{
    html_fin = paste(html_title,"
                     </body>",sep = "")
  }
  
  return(html_fin)
  }

pie_pop = create_popup(df_routes = df_routes,"Pietra di Bismantova")
pilot_pop = create_popup(df_routes = df_routes, "Pilot Mountain")
arco_pop = create_popup(df_routes = df_routes, "Arco")
sella_pop = create_popup(df_routes = df_routes, "Torri del Sella")
lagoni_pop = create_popup(df_routes = df_routes, "Lagoni")
bruno_pop = create_popup(df_routes = df_routes, "Sasso Bruno - Passo Pordoi")
malga_pop = create_popup(df_routes = df_routes, "Sasso Malga - Passo Sella")
fedaia_pop = create_popup(df_routes = df_routes, "Passo Fedaia")


df[1,"popup"] = pilot_pop
df[2,"popup"] = arco_pop
df[3,"popup"] = pie_pop
df[4,"popup"] = fedaia_pop
df[5,"popup"] = bruno_pop
df[6,"popup"] = malga_pop
df[7,"popup"] = sella_pop
df[8,"popup"] = lagoni_pop


final_map = leaflet(df) %>% addTiles() %>%
  addAwesomeMarkers(~lng, ~lat, icon=icons, label=~as.character(type),
                    popup =~ popup)
final_map
```

```{r map, echo = F}
final_map
```
